### ISSUE TITLE
localIdentName is not working for me

### ISSUE THREAD

**Issue by rolwin100** [xyy94813/customize-cra-less-loader#2]
@xyy94813 `localIdentName` is not working I want to add an `localIdentName` of type `myapp--[local]--[hash:base64:6]` . But its not working.

Below is the config I have added

```
addLessLoader({
      cssLoaderOptions: {
        sourceMap: true,
        modules: {
          localIdentName: "myapp--[local]--[hash:base64:6]",
        },
      },
      lessLoaderOptions: {
        lessOptions: {
          math: "always",
          javascriptEnabled: true,
          modifyVars: {
            "primary-color": "#007ED4",
          },
        },
      },
    }),
```

**Comment by xyy94813** [comment]
I ran into the same problem with `@dr.pogodin/babel-plugin-react-css-modules` before. 
Or check the version of css-loader and less-loader.

Hope this helps.

**Comment by xyy94813** [comment]
@rolwin100 

I will close this issue if it is resolved.
